# Generated by Django 3.1.4 on 2021-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(db_column='b_no', primary_key=True, serialize=False)),
                ('b_title', models.CharField(db_column='b_title', max_length=255)),
                ('b_content', models.TextField(db_column='b_content')),
                ('b_writer', models.CharField(db_column='b_writer', max_length=50)),
                ('parent_no', models.IntegerField(db_column='parent_no', default=0)),
                ('b_count', models.IntegerField(db_column='b_count', default=0)),
                ('b_date', models.DateTimeField(db_column='b_date')),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
    ]
