# Generated by Django 3.1.4 on 2021-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=10)),
                ('SubLine', models.CharField(max_length=15)),
                ('SubStation', models.CharField(max_length=50)),
            ],
        ),
    ]
